blog/urls.py
from django.urls import path

from .views import *

# from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('blog/posts/update/<str:pk>/', update_post, name="post_update"),
    path('blog/posts/delete/<str:pk>/', delete_post, name="post_delete"),
    path('<int:post_id>/share/', post_share, name="post_share"),
    
    path('new/blog/post/', new_blog_post, name="new_blog"),
    path('blog/posts/', user_blogs, name="user_blogs"),
    path('blog/posts/details/<str:pk>/', user_blog_detail, name="user_blog_detail"),
    
    path('pending/blog/posts/', user_pending_blogs, name="pending_blogs"),
    path('rejected/blog/posts/', user_rejected_blogs, name="rejected_blogs"),
    
    path('contact-us/', contact_us, name='contact_us')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/forms.py
from django import forms

from .models import Comment, ContactUs, Post


class BlogPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BlogPostForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = ('cover_image', 'title', 'body', 'status', 'featured')


class BlogPostUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BlogPostUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = ('cover_image', 'title', 'body', 'tags', 'status', 'featured')


class EmailPostForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        label="Your Full Name",
        widget=forms.TextInput()
    )
    email = forms.EmailField(label="Your Email")
    to = forms.EmailField(label="Reciever Email")
    comments = forms.CharField(
        required=False,
        label="Your Comment",
        widget=forms.Textarea(attrs={
            'placeholder': 'Please add some comments in the section so the reciever can know what this post is about out of the box. \n\nEg. Hi Mark this post talks about programming in dept, please check it out.'
        })
    )


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'We do not share your email or personal info'
            }
        )
    )

    body = forms.CharField(
        label="Your Comment",
        widget=forms.Textarea()
    )

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search for blogs...',
                'class': 'form-control my-1 p-3 fs-4  px-0 w-100',
                'type': 'search',
                'list': 'suggestions',
            }
        )
    )


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )

    telephone = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )

    
    class Meta:
        model = ContactUs
        fields = '__all__'

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from taggit.models import Tag


from .forms import *
from .models import *


@login_required
def new_blog_post(request):
    form = BlogPostForm()
    if request.method == "POST":
        form = BlogPostForm(request.POST, request.FILES,)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            title = obj.title
            obj.save()
            messages.success(
                request, f'Blog <b>"{title}"</b> Created successfully!')
            return redirect('blog:user_blogs')

    context = {
        'form': form,
    }

    return render(request, 'blog/post/new_blog.html', context)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    featured_posts = Post.published.filter(featured=True).order_by('-created')
    tag = None
    form = SearchForm()
    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:post_list')
            else:
                object_list = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # Tag Filter logic
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Pagination logic
    paginator = Paginator(object_list, 9)  # number of posts to show per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver the last page of the results
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'post_count': object_list.count(),
        'tag': tag,
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
        
        'featured_posts': featured_posts,
        'featured_posts_count': featured_posts.count(),
    }

    return render(request, 'blog/post/index.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                            publish__year=year, publish__month=month, publish__day=day)
    posts = Post.published.all()[:2]
    form = SearchForm()

    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:post_list')
            else:
                post = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # List Similar posts
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')

    # list the active comments for this post
    # we use post.comments.filter() bcos we added related_name='comment' to the comments model
    comments = post.comment.filter(active=True)

	# add comment login
    new_comment = None

    if request.method == "POST":
        # A comment was posted
        post_url = request.build_absolute_uri(post.get_absolute_url())
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create comment object but dont save to database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            # we are just updating the already stored data
            new_comment.post = post
            # save the comment to the database
            new_comment.save()
            messages.success(request, "New comment added successfully")
            return redirect(post_url)
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'posts': posts,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
    }

    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    # retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            # store form data in cd variable
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends {post.title}"
            message = f"""
			Blog Recommended By: {cd['name']}
			
			Blog title: {post.title}
			
			{cd['name']} Comments: {cd['comments']}
						
			Link to Blog: {post_url}
			"""
            send_mail(subject, message, 'admin@vedintechblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent
    }

    return render(request, 'blog/post/share.html', context)


def update_post(request, pk):
    post = Post.objects.get(id=pk)
    post_form = BlogPostUpdateForm(instance=post)

    if request.method == "POST":
        post_form = BlogPostUpdateForm(request.POST, request.FILES, instance=post)

        if post_form.is_valid():
            obj = post_form.save(commit=False)
            if not request.user.is_staff:
                obj.status = 'draft'
            obj.save()
            messages.success(request, "Blog post updated successfully")
            return redirect('blog:post_list')
        else:
            messages.error(request, "Error updating your profile")

    context = {
        'post_form': post_form
    }

    return render(request, 'blog/post/blog_update.html', context)


@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)
    title = post.title

    if request.method == "POST":
        messages.success(request, f"Blog post '{title}' deleted successfully")
        post.delete()
        return redirect('blog:post_list')
    else:
        messages.error(request, f"Error deleting blog '{title}'")
        return redirect('blog:post_list')


@login_required
def user_blogs(request):
    object_list = Post.objects.filter(author=request.user).order_by('-created')
    form = SearchForm()
    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:user_blogs')
            else:
                object_list = Post.objects.annotate(
                    search=SearchVector('title', 'body', 'status'),
                ).filter(search=query, author=request.user)
                blog_filtered = True

    # Pagination logic
    paginator = Paginator(object_list, 12)  # number of posts to show per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver the last page of the results
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'object_list': object_list.count(),
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
    }

    return render(request, 'blog/post/user_blogs.html', context)


@login_required
def user_blog_detail(request, pk):
    post = Post.objects.get(id=pk)
    form = SearchForm()
    query = None
    blog_filtered = False
    posts = Post.published.all()

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:user_blogs')
            else:
                object_list = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # List Similar posts
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:5]

    # list the active comments for this post
    # we use post.comments.filter() bcos we added related_name='comment' to the comments model
    comments = post.comment.filter(active=True)

    context = {
        'post': post,
        'posts': posts,
        'comments': comments,

templates/blog/partials/main_nav.html
{% if request.user.is_authenticated %}

{% include "../partials/main_messages.html" %}
<header class="navigation">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'blog:post_list' %}">
			<span class="text-info"><i class="bi bi-vinyl"></i></span>
			<span class="text-info">VED</span><span class="text-danger">IN</span><span class="text-dark">TECH</span>
		</a>
		<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
			aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse text-center" id="navogation">
			<ul class="navbar-nav m-auto">
				<li class="nav-item">
					<a class="nav-link text-uppercase text-dark" href="{% url 'blog:post_list' %}">Blogs</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-uppercase text-dark" href="{% url 'blog:contact_us' %}">Contact</a>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
						role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						{{request.user.username}}
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
						<a class="dropdown-item" href="{% url 'blog:user_blogs' %}">My Blogs</a>
						<a class="dropdown-item" href="{% url 'blog:new_blog' %}">Create New Blog</a>
						<hr>
						{% if request.user.is_staff %}
						<a class="dropdown-item" href="{% url 'all_users' %}">All Users</a>
						<a class="dropdown-item" href="{% url 'blog:pending_blogs' %}">
							Pending Blogs
							<!-- {% if posts.status == 'published' %}
							<span class="badge badge-danger">4</span>
							{% endif %} -->
						</a>
						<a class="dropdown-item" href="{% url 'blog:rejected_blogs' %}">Rejected Blogs</a>
						<hr>
						{% endif %}

						<a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
						<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
					</div>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
						role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						DOCS
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#">How to write a post</a>
						<a class="dropdown-item" href="#">The Rich Text Editor</a>
						<hr>
						<a class="dropdown-item"
							href="https://github.com/Victorspy-web/advanced-blogging-website">Source Code</a>
					</div>
				</li>
			</ul>

			<form class="form-inline position-relative ml-lg-4">
				{{form}}
				<datalist id="suggestions">
					{% for post in posts %}
					<!--|slice:"5" -->
					<option value="{{post.title}}">{{post.body|striptags|truncatewords_html:3}}</option>
					{% endfor %}
				</datalist>
				<a href="#" class="search-icon"><i class="ti-search text-dark"></i></a>
			</form>
			<datalist id="suggestions">
				{% for post in posts %}
				<option value="{{post.title}}">{{post.body|striptags|truncatewords_html:3}}</option>
				{% endfor %}
			</datalist>

		</div>
	</nav>
</header>

{% else %}
{% include "../partials/main_messages.html" %}
<header class="navigation">
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand" href="{% url 'blog:post_list' %}">
			<span class="text-info"><i class="bi bi-vinyl"></i></span>
			<span class="text-info">VED</span><span class="text-danger">IN</span><span class="text-dark">TECH</span>
		</a>
		<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
			aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse text-center" id="navogation">
			<ul class="navbar-nav m-auto">
				<li class="nav-item">
					<a class="nav-link text-uppercase text-dark" href="{% url 'blog:post_list' %}">Blogs</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-uppercase text-dark" href="{% url 'blog:contact_us' %}">Contact</a>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link text-uppercase text-dark dropdown-toggle" href="#" id="navbarDropdown"
						role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						MORE LINKS
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'login' %}">Login</a>
						<a class="dropdown-item" href="{% url 'register' %}">Register</a>
						<a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a>
						<hr>
						<a class="dropdown-item" href="https://github.com/Victorspy-web/advanced-blogging-website"
							target="_blank">Source Code</a>
					</div>
				</li>
			</ul>
			<form class="form-inline position-relative ml-lg-4">
				{{form}}
				<datalist id="suggestions">
					{% for post in posts %}
					<!--|slice:"5" -->
					<option value="{{post.title}}">{{post.body|striptags|truncatewords_html:3}}</option>
					{% endfor %}
				</datalist>
				<a href="search.html" class="search-icon"><i class="ti-search text-dark"></i></a>
			</form>
		</div>
	</nav>
</header>
{% endif %}

templates/blog/partials/navbar.html
<!-- Navbar -->
{% if request.user.is_authenticated %}

{% include "../partials/messages.html" %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top p-4">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'blog:post_list' %}">
			<span class="text-info"><i class="bi bi-vinyl"></i></span>
			<span class="text-info">VED</span><span class="text-danger">IN</span><span class="text-dark">TECH</span>
		</a>
		<button class="navbar-toggler border-none text-dark rounded-pill" type="button" data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
			aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav m-auto">

				<li class="nav-item text-uppercase">
					<a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Blogs</a>
				</li>

				<li class="nav-item text-uppercase">
					<a class="nav-link active" aria-current="page" href="{% url 'blog:contact_us' %}">Contact Us</a>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
						data-bs-toggle="dropdown" aria-expanded="false">
						{{request.user.username|upper}}
					</a>
					<ul class="dropdown-menu p-4" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
						<li><a class="dropdown-item" href="{% url 'blog:user_blogs' %}">My Blogs</a></li>
						<li><a class="dropdown-item" href="{% url 'blog:new_blog' %}">Create New Blog</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						{% if request.user.is_staff %}
						<li><a class="dropdown-item" href="{% url 'all_users' %}">All Users</a></li>
						<li><a class="dropdown-item" href="{% url 'blog:pending_blogs' %}">Pending Blogs</a></li>
						<li><a class="dropdown-item" href="{% url 'blog:rejected_blogs' %}">Rejected Blogs</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						{% endif %}
						<li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
						<li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
					</ul>
				</li>

				<li class="nav-item dropdown ms-auto">
					<a class="nav-link dropdown-toggle text-uppercase active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
						aria-expanded="false">
						Docs
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="#">How to write a post</a></li>
						<li><a class="dropdown-item" href="#">The Rich Text Editor</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						<li><a class="dropdown-item" href="https://github.com/Victorspy-web/advanced-blogging-website" target="_blank">Source Code</a></li>

					</ul>
				</li>
			</ul>

		</div>
	</div>
</nav>

{% else %}
{% include "../partials/messages.html" %}
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top shadow p-4">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'blog:post_list' %}">
			<span class="text-info"><i class="bi bi-vinyl"></i></span>
			<span class="text-info">VED</span><span class="text-danger">IN</span><span class="text-dark">TECH</span>
		</a>
		<button class="navbar-toggler border-none text-dark rounded-pill" type="button" data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
			aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav m-auto">
				<li class="nav-item">
					<a class="nav-link text-uppercase active" aria-current="page" href="{% url 'blog:post_list' %}">Blogs</a>
				</li>

				<li class="nav-item">
					<a class="nav-link text-uppercase active" aria-current="page" href="{% url 'blog:contact_us' %}">Contact</a>
				</li>

				<li class="nav-item dropdown me-auto">
					<a class="nav-link dropdown-toggle text-uppercase active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
						aria-expanded="false">
						More Links
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
						<li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
						<li><a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a></li>
						<li><a class="dropdown-item" href="https://github.com/Victorspy-web/advanced-blogging-website" target="_blank">Source Code</a></li>
					</ul>
				</li>
			</ul>

		</div>
	</div>
</nav>
{% endif %}
<!-- end Nav -->

templates/blog/partials/sidebar.html
{% load blog_tags %}
<div class="col-lg-4">

	{% if post.tags %}
	<div class="widget">
		<h6 class="mb-4">TAGS</h6>
		<ul class="list-inline tag-list">
			{% for tag in post.tags.all %}
			<li class="list-inline-item m-1"><a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a></li>
			{% if not forloop.last %} {% endif %}
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	{% if similar_posts %}
	<div class="widget">
		<h6 class="mb-4">SIMILAR POSTS</h6>
		{% for post in similar_posts|slice:":2" %}
		<div class="media mb-4">
			<div class="post-thumb-sm mr-3">
				<img class="img-fluid latest-posts-img" src="{{post.cover_image.url}}" alt="post-thumb">
			</div>
			<div class="media-body">
				<ul class="list-inline d-flex justify-content-between mb-2">
					<li class="list-inline-item">Post By {{post.author.username}}</li>
					<li class="list-inline-item">{{post.publish}}</li>
				</ul>
				<h6><a class="text-dark"
						href="{{ post.get_absolute_url }}">{{post.title|striptags|truncatewords_html:5}}</a>
				</h6>
			</div>
		</div>
		{% endfor %}
	</div>
	{% endif %}

	{% if posts %}
	<div class="widget">
		<h6 class="mb-4">LATEST POST</h6>
		{% for post in posts|slice:":2" %}
		<div class="media mb-4">
			<div class="post-thumb-sm mr-3">
				<img class="img-fluid latest-posts-img" src="{{post.cover_image.url}}" alt="post-thumb">
			</div>
			<div class="media-body">
				<ul class="list-inline d-flex justify-content-between mb-2">
					<li class="list-inline-item">Post By {{post.author.username}}</li>
					<li class="list-inline-item">{{post.publish}}</li>
				</ul>
				<h6><a class="text-dark"
						href="{{ post.get_absolute_url }}">{{post.title|striptags|truncatewords_html:5}}</a>
				</h6>
			</div>
		</div>
		{% endfor %}
	</div>
	{% endif %}

	{% get_most_commented_posts 2  as most_commented_posts%}
	{% if most_commented_posts %}
	<div class="widget">
		<h6 class="mb-4">MOST COMMENTED POST</h6>
		{% for post in most_commented_posts %}
		<div class="media mb-4">
			<div class="post-thumb-sm mr-3">
				<img class="img-fluid latest-posts-img" src="{{post.cover_image.url}}" alt="post-thumb">
			</div>
			<div class="media-body">
				<ul class="list-inline d-flex justify-content-between mb-2">
					<li class="list-inline-item">Post By {{post.author.username}}</li>
					<li class="list-inline-item">{{post.publish}}</li>
				</ul>
				<h6><a class="text-dark"
						href="{{ post.get_absolute_url }}">{{post.title|striptags|truncatewords_html:5}}</a>
				</h6>
			</div>
		</div>
		{% endfor %}
	</div>
	{% endif %}

</div>