blog/urls.py
from django.urls import path

from .views import *

# from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('blog/posts/update/<str:pk>/', update_post, name="post_update"),
    path('blog/posts/delete/<str:pk>/', delete_post, name="post_delete"),
    path('<int:post_id>/share/', post_share, name="post_share"),
    
    path('new/blog/post/', new_blog_post, name="new_blog"),
    path('blog/posts/', user_blogs, name="user_blogs"),
    path('blog/posts/details/<str:pk>/', user_blog_detail, name="user_blog_detail"),
    
    path('pending/blog/posts/', user_pending_blogs, name="pending_blogs"),
    path('rejected/blog/posts/', user_rejected_blogs, name="rejected_blogs"),
    
    path('contact-us/', contact_us, name='contact_us')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/forms.py
from django import forms

from .models import Comment, ContactUs, Post


class BlogPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BlogPostForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = ('cover_image', 'title', 'body', 'status', 'featured')


class BlogPostUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BlogPostUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = ('cover_image', 'title', 'body', 'tags', 'status', 'featured')


class EmailPostForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        label="Your Full Name",
        widget=forms.TextInput()
    )
    email = forms.EmailField(label="Your Email")
    to = forms.EmailField(label="Reciever Email")
    comments = forms.CharField(
        required=False,
        label="Your Comment",
        widget=forms.Textarea(attrs={
            'placeholder': 'Please add some comments in the section so the reciever can know what this post is about out of the box. \n\nEg. Hi Mark this post talks about programming in dept, please check it out.'
        })
    )


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'We do not share your email or personal info'
            }
        )
    )

    body = forms.CharField(
        label="Your Comment",
        widget=forms.Textarea()
    )

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search for blogs...',
                'class': 'form-control my-1 p-3 fs-4  px-0 w-100',
                'type': 'search',
                'list': 'suggestions',
            }
        )
    )


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )

    telephone = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-4',
            }
        )
    )

    
    class Meta:
        model = ContactUs
        fields = '__all__'

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from taggit.models import Tag


from .forms import *
from .models import *


@login_required
def new_blog_post(request):
    form = BlogPostForm()
    if request.method == "POST":
        form = BlogPostForm(request.POST, request.FILES,)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            title = obj.title
            obj.save()
            messages.success(
                request, f'Blog <b>"{title}"</b> Created successfully!')
            return redirect('blog:user_blogs')

    context = {
        'form': form,
    }

    return render(request, 'blog/post/new_blog.html', context)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    featured_posts = Post.published.filter(featured=True).order_by('-created')
    tag = None
    form = SearchForm()
    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:post_list')
            else:
                object_list = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # Tag Filter logic
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Pagination logic
    paginator = Paginator(object_list, 9)  # number of posts to show per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver the last page of the results
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'post_count': object_list.count(),
        'tag': tag,
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
        
        'featured_posts': featured_posts,
        'featured_posts_count': featured_posts.count(),
    }

    return render(request, 'blog/post/index.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                            publish__year=year, publish__month=month, publish__day=day)
    posts = Post.published.all()[:2]
    form = SearchForm()

    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:post_list')
            else:
                post = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # List Similar posts
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')

    # list the active comments for this post
    # we use post.comments.filter() bcos we added related_name='comment' to the comments model
    comments = post.comment.filter(active=True)

	# add comment login
    new_comment = None

    if request.method == "POST":
        # A comment was posted
        post_url = request.build_absolute_uri(post.get_absolute_url())
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create comment object but dont save to database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            # we are just updating the already stored data
            new_comment.post = post
            # save the comment to the database
            new_comment.save()
            messages.success(request, "New comment added successfully")
            return redirect(post_url)
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'posts': posts,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
    }

    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    # retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            # store form data in cd variable
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends {post.title}"
            message = f"""
			Blog Recommended By: {cd['name']}
			
			Blog title: {post.title}
			
			{cd['name']} Comments: {cd['comments']}
						
			Link to Blog: {post_url}
			"""
            send_mail(subject, message, 'admin@vedintechblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent
    }

    return render(request, 'blog/post/share.html', context)


def update_post(request, pk):
    post = Post.objects.get(id=pk)
    post_form = BlogPostUpdateForm(instance=post)

    if request.method == "POST":
        post_form = BlogPostUpdateForm(request.POST, request.FILES, instance=post)

        if post_form.is_valid():
            obj = post_form.save(commit=False)
            if not request.user.is_staff:
                obj.status = 'draft'
            obj.save()
            messages.success(request, "Blog post updated successfully")
            return redirect('blog:post_list')
        else:
            messages.error(request, "Error updating your profile")

    context = {
        'post_form': post_form
    }

    return render(request, 'blog/post/blog_update.html', context)


@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)
    title = post.title

    if request.method == "POST":
        messages.success(request, f"Blog post '{title}' deleted successfully")
        post.delete()
        return redirect('blog:post_list')
    else:
        messages.error(request, f"Error deleting blog '{title}'")
        return redirect('blog:post_list')


@login_required
def user_blogs(request):
    object_list = Post.objects.filter(author=request.user).order_by('-created')
    form = SearchForm()
    query = None
    blog_filtered = False

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:user_blogs')
            else:
                object_list = Post.objects.annotate(
                    search=SearchVector('title', 'body', 'status'),
                ).filter(search=query, author=request.user)
                blog_filtered = True

    # Pagination logic
    paginator = Paginator(object_list, 12)  # number of posts to show per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver the last page of the results
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'object_list': object_list.count(),
        'form': form,
        'query': query,
        'blog_filtered': blog_filtered,
    }

    return render(request, 'blog/post/user_blogs.html', context)


@login_required
def user_blog_detail(request, pk):
    post = Post.objects.get(id=pk)
    form = SearchForm()
    query = None
    blog_filtered = False
    posts = Post.published.all()

    # Blog Search Filter logic
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            if query == '' or query == None:
                return redirect('blog:user_blogs')
            else:
                object_list = Post.published.annotate(
                    search=SearchVector('title', 'body'),
                ).filter(search=query)
                blog_filtered = True

    # List Similar posts
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:5]

    # list the active comments for this post
    # we use post.comments.filter() bcos we added related_name='comment' to the comments model
    comments = post.comment.filter(active=True)

    context = {
        'post': post,
        'posts': posts,
        'comments': comments,

templates/blog/post/detail.html
{% extends "blog/partials/main_base.html" %}
{% block title %}{{post.title}} - Blog{% endblock title %}
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

{% if tag or blog_filtered %}
{% include "blog/post/search.html" %}
{% else %}

<!-- page-title -->
<section class="section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="blog-detail-cover-image pt-4">
					<span class="d-flex justify-content-center p-5">
						<h4 class=" text-white">{{post.title}}</h4>
					</span>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /page-title -->

<!-- blog single -->
<section>
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<ul class="list-inline d-flex justify-content-between py-3">
					<li class="list-inline-item"><i class="ti-user mr-2"></i>Post by {{post.author.username}}</li>
					<li class="list-inline-item"><i class="ti-calendar mr-2"></i>{{post.publish}}</li>
				</ul>
				<div class="content">
					<p>{{post.body|safe|linebreaks}}</p>
				</div>

				<!-- Share Post Through Google -->
				<p class="py-2">
					<div class="row">
						<a class="btn btn-primary btn-lg col-md-3 m-2" role="button"
							href="{% url 'blog:post_share' post.id %}">
							Share Via Mail
							<i class="text-danger bi bi-google"></i>
						</a>
						{% if request.user.is_authenticated %}
						{% if request.user.id == post.author.id or request.user.is_staff%}
						<a class="btn btn-info btn-lg col-md-3 m-2" href="{% url 'blog:post_update' post.id %}">
							Edit Post
							<span class="text-dark">
								<i class="bi bi-pencil-square"></i>
							</span>
						</a>

						<!-- Button trigger modal -->
						<button type="button" class="btn btn-danger btn-lg col-md-3 m-2" data-toggle="modal"
							data-target="#exampleModal">
							Delete Post
							<span class="text-light">
								<i class="bi bi-trash-fill"></i>
							</span>
						</button>

						<!-- Modal -->
						<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
							aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete
											blog "{{post.title}}</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<div class="modal-body">
										<form action="{% url 'blog:post_delete' post.pk %}" method="post">
											{% csrf_token %}
											<input class="btn btn-danger btn-lg col-md-5 m-2" type="submit"
												value="Yes!">

											<a class="btn btn-info btn-lg col-md-5 m-2"
												href="{% url 'blog:post_list' %}">
												No, Cancel!
											</a>
										</form>
									</div>
								</div>
							</div>
						</div>
						{% endif %}
						{% endif %}

					</div>
				</p>

				<div class="col-12 comment-container my-4">
					{% with comments.count as total_comments %}
					<h3 class="text-center">
						{{ total_comments }} comment{{ total_comments|pluralize }}
					</h3>
					{% endwith %}
					<hr>

					{% for comment in comments %}
					<div class="border-left border-5 border-dark border-5 px-2 mb-5">
						<h5 class="fw-bolder">
							<span class="bg-primary rounded p-2 text-white">{{comment.name|upper|slice:"1"}}</span>
							{{comment.name}}
						</h5>
						<div>
							{{ comment.body|linebreaks }}
						</div>
					</div>
					{% empty %}
					<h4 class="text-center pb-4">There are no comments!</h4>
					{% endfor %}
				</div>

				<button type="button" class="btn btn-primary col-12 mx-2 h4" data-toggle="modal"
					data-target="#modal-default">
					<i class="bi bi-trash"></i>
					Add Comment
				</button>

				<div class="modal fade" id="modal-default">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h4 class="modal-title">Add New Comment</h4>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<form action="" method="POST" enctype="multipart/form-data">
								{% csrf_token %}
								<div class="form-group mx-2">
									{{comment_form.as_p}}
								</div>
								<div class="modal-footer justify-content-around">
									<input type="submit" class="btn btn-danger" value="Add new comment">
									<button type="button" class="btn btn-info" data-dismiss="modal">No
										,Cancel!</button>
								</div>
							</form>
						</div>
						<!-- /.modal-content -->
					</div>
					<!-- /.modal-dialog -->
				</div>

			</div>

			<!-- side bar -->
			{% include "blog/partials/sidebar.html" %}

		</div>
	</div>
</section>
<!-- /blog single -->

<!-- <div class="row py-2 mt-5">
<div class="col-lg-5 col-md-8 col-sm-8 mx-2">
		<h3 class="text-center">Add a comment</h3>
		<form action="" method="POST">
			{% csrf_token %}
			{{comment_form|crispy}}
			<span class=" d-flex justify-content-center">
				<input type="submit" class="btn btn-primary btn-lg my-2 col-12" value="Add Comment">
			</span>
		</form>
	</div>
</div> -->
{% endif %}

{% endblock content %}

templates/blog/post/latest_posts.html
<!-- This is the custom inclusion_tag i created -->
<div class="row">
	{% for post in latest_posts %}
	<a class="text-dark fs-6 py-1 sidebar-link" href="{{ post.get_absolute_url }}">
		{{post.title}}
	</a>
	{% endfor %}
</div>

templates/blog/post/user_blog_details.html
{% extends "blog/partials/main_base.html" %}
{% block title %}User Blog Details Page{% endblock title %}
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
{% if tag or blog_filtered %}
{% include "blog/post/search.html" %}
{% else %}
<!-- page-title -->
<section class="section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="blog-detail-cover-image pt-4">
					<span class="d-flex justify-content-center p-5">
						<h4 class="text-white">{{post.title}} -
							{% if post.status == "draft" %}
							<span class="text-info">Status: Pending</span>
							{% endif %}

							{% if post.status == "published" %}
							<span class="text-info">Status: Published</span>
							{% endif %}

							{% if post.status == "rejected" %}
							<span class="text-info">Status: Rejected</span>
							{% endif %}
						</h4>
					</span>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /page-title -->

<!-- blog single -->
<section>
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<ul class="list-inline d-flex justify-content-between py-3">
					<li class="list-inline-item"><i class="ti-user mr-2"></i>Post by {{post.author.username}}</li>
					<li class="list-inline-item"><i class="ti-calendar mr-2"></i>{{post.publish}}</li>
				</ul>
				<div class="content">
					<p>{{post.body|safe|linebreaks}}</p>
				</div>

				<!-- Share Post Through Google -->
				<p class="py-2">
					<div class="row">
						{% if post.status == "published" %}
						<a class="btn btn-primary btn-lg col-md-3 m-2" role="button"
							href="{% url 'blog:post_share' post.id %}">
							Share post
							<i class="text-danger bi bi-google"></i>
						</a>
						{% endif %}
						{% if request.user.is_authenticated %}
						{% if request.user.id == post.author.id or request.user.is_staff%}
						<a class="btn btn-info btn-lg col-md-3 m-2" href="{% url 'blog:post_update' post.id %}">
							Edit Post
							<span class="text-dark">
								<i class="bi bi-pencil-square"></i>
							</span>
						</a>

						<!-- Button trigger modal -->
						<button type="button" class="btn btn-danger btn-lg col-md-3 m-2" data-toggle="modal"
							data-target="#exampleModal">
							Delete Post
							<span class="text-light">
								<i class="bi bi-trash-fill"></i>
							</span>
						</button>

						<!-- Modal -->
						<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
							aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete
											blog "{{post.title}}</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<div class="modal-body">
										<form action="{% url 'blog:post_delete' post.pk %}" method="post">
											{% csrf_token %}
											<input class="btn btn-danger btn-lg col-md-5 m-2" type="submit"
												value="Yes!">

											<a class="btn btn-info btn-lg col-md-5 m-2"
												href="{% url 'blog:post_list' %}">
												No, Cancel!
											</a>
										</form>
									</div>
								</div>
							</div>
						</div>

						{% endif %}
						{% endif %}
					</div>
				</p>
				<div class="col-12 comment-container">
					{% with comments.count as total_comments %}
					<h3 class="text-center">
						{{ total_comments }} comment{{ total_comments|pluralize }}
					</h3>
					{% endwith %}
					<hr>

					{% for comment in comments %}
					<div class="border-left border-5 border-dark border-5 px-2 mb-5">
						<h5 class="fw-bolder">
							<span class="bg-primary rounded p-2 text-white">{{comment.name|upper|slice:"1"}}</span>
							{{comment.name}}
						</h5>
						<div>
							{{ comment.body|linebreaks }}
						</div>
					</div>
					{% empty %}
					<h4 class="text-center pb-4">There are no comments!</h4>
					{% endfor %}
				</div>
			</div>

			<!-- side bar -->
			{% include "blog/partials/sidebar.html" %}

		</div>
	</div>
</section>
<!-- /blog single -->

{% endif %}
{% endblock content %}

templates/blog/post/user_pending_blogs.html
{% extends "blog/partials/main_base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}User Blogs Page{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
{% if request.user.is_staff %}
<!-- page-title -->
<section class="section">
	<div class="container-fluid">
		<div class="blog-detail-cover-image pt-3">
			<span class="d-flex justify-content-center p-5">
				<h4 class="text-white">
					All Pending Blogs
				</h4>

			</span>

		</div>
</section>
<!-- /page-title -->

<!-- search result -->
<section class="section">
	<div class="container">
		<div class="row">
			{% for post in posts %}
			<div class="col-lg-10 mx-auto">
				<ul class="list-unstyled">

					<li class="border-bottom mb-4 pb-3">
						<h4><a href="{% url 'blog:user_blog_detail' post.pk %}" class="text-dark">{{ post.title }}</a> -
							<span>
								{% if post.status == "draft" %}
								Status: <span class="text-info">Pending</span>
								{% endif %}

								{% if post.status == "published" %}
								Status: <span class="text-info">Published</span>
								{% endif %}

								{% if post.status == "rejected" %}
								Status: <span class="text-info">Rejected</span>
								{% endif %}
							</span></h4>
						<p>{{post.publish}} - Author {{post.author.username}}</p>
						<p>{{post.body|striptags|truncatewords_html:30}}</p>
						<a href="{% url 'blog:user_blog_detail' post.pk %}" class="btn btn-transparent pl-0">Read More</a>
					</li>

				</ul>
			</div>
			{% empty %}
			<div class="text-center mx-auto">
				{% if blog_filtered %}
				<h3 class="py-5">Oops, No Blogs found...</h3>
				<a class="btn btn-success btn-lg" href="{% url 'blog:pending_blogs' %}">Back To Blogs</a>
				{% else %}
				<h3 class="my-5">There are no pending blogs...</h3>
				<a class="btn btn-success btn-lg" href="{% url 'blog:new_blog' %}">Create A New Blog</a>
				{% endif %}
			</div>
			{% endfor %}



		</div>
	</div>
</section>
<!-- /search result -->

{% endif %}
{% endif %}

{% if post_count > 9 %}
{% include "blog/partials/pagination.html" %}
{% endif %}
{% endblock content %}

templates/blog/post/user_rejected_blogs.html
{% extends "blog/partials/main_base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}User Blogs Page{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
{% if request.user.is_staff %}
<!-- page-title -->
<section class="section">
	<div class="container-fluid">
		<div class="blog-detail-cover-image pt-3">
			<span class="d-flex justify-content-center p-5">
				<h4 class="text-white">
					All Rejected Blogs
				</h4>

			</span>

		</div>
</section>
<!-- /page-title -->

<!-- search result -->
<section class="section">
	<div class="container">
		<div class="row">
			{% for post in posts %}
			<div class="col-lg-10 mx-auto">
				<ul class="list-unstyled">

					<li class="border-bottom mb-4 pb-3">
						<h4><a href="{% url 'blog:user_blog_detail' post.pk %}" class="text-dark">{{ post.title }}</a> -
							<span>
								{% if post.status == "draft" %}
								Status: <span class="text-info">Pending</span>
								{% endif %}

								{% if post.status == "published" %}
								Status: <span class="text-info">Published</span>
								{% endif %}

								{% if post.status == "rejected" %}
								Status: <span class="text-info">Rejected</span>
								{% endif %}
							</span></h4>
						<p>{{post.publish}} - Author {{post.author.username}}</p>
						<p>{{post.body|striptags|truncatewords_html:30}}</p>
						<a href="{% url 'blog:user_blog_detail' post.pk %}" class="btn btn-transparent pl-0">Read More</a>
					</li>

				</ul>
			</div>
			{% empty %}
			<div class="text-center mx-auto">
				{% if blog_filtered %}
				<h3 class="py-5">Oops, No Blogs found...</h3>
				<a class="btn btn-success btn-lg" href="{% url 'blog:rejected_blogs' %}">Back To Blogs</a>
				{% else %}
				<h3 class="my-5">There are no rejected blogs...</h3>
				<a class="btn btn-success btn-lg" href="{% url 'blog:new_blog' %}">Create A New Blog</a>
				{% endif %}
			</div>
			{% endfor %}



		</div>
	</div>
</section>
<!-- /search result -->

{% endif %}
{% endif %}

{% if post_count > 9 %}
{% include "blog/partials/pagination.html" %}
{% endif %}
{% endblock content %}